{{- if and (and .Values.autotrace.instrumentation.imagePullCredentials.registry .Values.autotrace.instrumentation.imagePullCredentials.username) .Values.autotrace.instrumentation.imagePullCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: instana-init-pull-secret
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "instana-autotrace-webhook.init.imagePullSecret" . }}
{{- end }}