{{- if eq (include "instana-autotrace-webhook.hasImagePullCredentials" .) "false" }}
{{- include "instana-autotrace-webhook.setImagePullCredentialsWarning" . }}
{{- end }}
{{- if and (eq (include "instana-autotrace-webhook.hasImagePullCredentials" .) "true") (hasPrefix "containers.instana.io/" .Values.webhook.image) (eq (len .Values.webhook.imagePullSecrets) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: containers-instana-io
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "instana-autotrace-webhook.webhook.imagePullSecret" . }}
{{- end }}
