{{- if or .Values.rbac.enabled .Values.openshift.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-clusterrole
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  resourceNames: ["*"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  resourceNames: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  resourceNames: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps.openshift.io"]
  resources: ["deploymentconfigs"]
  resourceNames: ["*"]
  verbs: ["get", "list", "watch"]
{{ if .Values.webhook.pod.hostNetwork }}
- apiGroups: ["security.openshift.io"]
  resourceNames: ["hostnetwork"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-binding
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
