# Pre-install job to clean up existing secrets without Helm ownership annotations
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cleanup-orphans
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
  labels:
    {{- include "instana-autotrace-webhook.commonLabels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-cleanup-orphans
      labels:
        {{- include "instana-autotrace-webhook.commonLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-cleanup-sa
      restartPolicy: Never
      containers:
      - name: cleanup-secrets
        image: registry.k8s.io/kubectl:{{ default .Capabilities.KubeVersion.GitVersion "v1.29.0"}}
        args:
        - delete
        - secret
        - instana-autotrace-webhook-certs
        - --ignore-not-found=true
        - --v=2

