# These values override some of the values set in the values.yaml and are used when
# developing against locally built images and pushed to the local registry to be used
# with minikube
webhook:
  image: myregistry:5000/instana-autotrace-webhook:local
  debug: true

autotrace:
  instrumentation:
    image: myregistry:5000/instana/instrumentation:local
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1001
      capabilities:
        drop:
          - all
  ingress_nginx:
    enabled: true
  ace:
    enabled: true
  ibmmq:
    enabled: true
